/** Data List
const dataApi = []
module.exports = dataApi; */

const dataApi = [
  {
    "country_id": "1",
    "country": "Afghanistan",
    "name_of_holiday": "Afghan Independence Day",
    "date_of_holiday": "19/08",
    "date_num": "1908",
    "month_of_event": "August",
    "year_of_event": "1919",
    "independence_from": "United Kingdom",
    "capital": "Kabul"
  },
  {
    "country_id": "2",
    "country": "Albania",
    "name_of_holiday": "Flag Day",
    "date_of_holiday": "28/11",
    "date_num": "2811",
    "month_of_event": "November",
    "year_of_event": "1912",
    "independence_from": "Ottoman Empire",
    "capital": "Tirana"
  },
  {
    "country_id": "3",
    "country": "Algeria",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "05/07",
    "date_num": "0507",
    "month_of_event": "July",
    "year_of_event": "1962",
    "independence_from": "France",
    "capital": "Algiers [El Djazaïr]"
  },
  {
    "country_id": "4",
    "country": "Angola",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "11/11",
    "date_num": "1111",
    "month_of_event": "November",
    "year_of_event": "1975",
    "independence_from": "Portugal",
    "capital": "Luanda"
  },
  {
    "country_id": "5",
    "country": "Antigua and Barbuda",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/11",
    "date_num": "0111",
    "month_of_event": "November",
    "year_of_event": "1981",
    "independence_from": "United Kingdom",
    "capital": "Saint John's"
  },
  {
    "country_id": "6",
    "country": "Argentina",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "09/07",
    "date_num": "0907",
    "month_of_event": "July",
    "year_of_event": "1816",
    "independence_from": "Spanish Empire",
    "capital": "Buenos Aires"
  },
  {
    "country_id": "7",
    "country": "Armenia",
    "name_of_holiday": "Republic Day",
    "date_of_holiday": "28/05",
    "date_num": "2805",
    "month_of_event": "May",
    "year_of_event": "1918",
    "independence_from": "Russian Soviet Federative Socialist Republic",
    "capital": "Yerevan"
  },
  {
    "country_id": "8",
    "country": "Armenia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "21/09",
    "date_num": "2109",
    "month_of_event": "September",
    "year_of_event": "1991",
    "independence_from": "Soviet Union",
    "capital": "Yerevan"
  },
  {
    "country_id": "9",
    "country": "Azerbaijan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "28/05",
    "date_num": "2805",
    "month_of_event": "May",
    "year_of_event": "1918",
    "independence_from": "Russian Soviet Federative Socialist Republic",
    "capital": "Baku"
  },
  {
    "country_id": "10",
    "country": "Azerbaijan",
    "name_of_holiday": "Independendence Restoration Day",
    "date_of_holiday": "18/10",
    "date_num": "1810",
    "month_of_event": "October",
    "year_of_event": "1991",
    "independence_from": "Soviet Union",
    "capital": "Baku"
  },
  {
    "country_id": "11",
    "country": "Bahamas, The",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "10/07",
    "date_num": "1007",
    "month_of_event": "July",
    "year_of_event": "1973",
    "independence_from": "United Kingdom",
    "capital": "Nassau"
  },
  {
    "country_id": "12",
    "country": "Bahrain",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "16/12",
    "date_num": "1612",
    "month_of_event": "December",
    "year_of_event": "1971",
    "independence_from": "",
    "capital": "Manama"
  },
  {
    "country_id": "13",
    "country": "Bangladesh",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "26/03",
    "date_num": "2603",
    "month_of_event": "March",
    "year_of_event": "1971",
    "independence_from": "Pakistan",
    "capital": "Dhaka"
  },
  {
    "country_id": "14",
    "country": "Bangladesh",
    "name_of_holiday": "Victory Day",
    "date_of_holiday": "16/12",
    "date_num": "1612",
    "month_of_event": "December",
    "year_of_event": "1971",
    "independence_from": "",
    "capital": "Dhaka"
  },
  {
    "country_id": "15",
    "country": "Barbados",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "30/11",
    "date_num": "3011",
    "month_of_event": "November",
    "year_of_event": "1966",
    "independence_from": "United Kingdom",
    "capital": "Bridgetown"
  },
  {
    "country_id": "16",
    "country": "Belarus",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "03/07",
    "date_num": "0307",
    "month_of_event": "July",
    "year_of_event": "1991",
    "independence_from": "Soviet Union",
    "capital": "Minsk"
  },
  {
    "country_id": "17",
    "country": "Belgium",
    "name_of_holiday": "National Day",
    "date_of_holiday": "21/07",
    "date_num": "2107",
    "month_of_event": "July",
    "year_of_event": "1831",
    "independence_from": "United Netherlands"
  },
  {
    "country_id": "18",
    "country": "Belize",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "21/09",
    "date_num": "2109",
    "month_of_event": "September",
    "year_of_event": "1981",
    "independence_from": "United Kingdom",
    "capital": "Belmopan"
  },
  {
    "country_id": "19",
    "country": "Benin",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/08",
    "date_num": "0108",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "France",
    "capital": "Porto-Novo"
  },
  {
    "country_id": "20",
    "country": "Bhutan",
    "name_of_holiday": "National Day",
    "date_of_holiday": "17/12",
    "date_num": "1712",
    "month_of_event": "December",
    "year_of_event": "1907",
    "independence_from": "",
    "capital": "Thimphu"
  },
  {
    "country_id": "21",
    "country": "Bolivia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "06/08",
    "date_num": "0608",
    "month_of_event": "August",
    "year_of_event": "1825",
    "independence_from": "Spain",
    "capital": "Sucre"
  },
  {
    "country_id": "22",
    "country": "Bosnia and Herzegovina",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/03",
    "date_num": "0103",
    "month_of_event": "March",
    "year_of_event": "1992",
    "independence_from": "Socialist Federal Republic of Yugoslavia",
    "capital": "Sarajevo"
  },
  {
    "country_id": "23",
    "country": "Botswana",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "30/09",
    "date_num": "3009",
    "month_of_event": "September",
    "year_of_event": "1966",
    "independence_from": "United Kingdom",
    "capital": "Gaborone"
  },
  {
    "country_id": "24",
    "country": "Brazil",
    "name_of_holiday": "Independence Day (Dia da Independência)",
    "date_of_holiday": "07/09",
    "date_num": "0709",
    "month_of_event": "September",
    "year_of_event": "1822",
    "independence_from": "United Kingdom of Portugal, Brazil and the Algarves",
    "capital": "Brasília"
  },
  {
    "country_id": "25",
    "country": "Brunei",
    "name_of_holiday": "National Day",
    "date_of_holiday": "23/02",
    "date_num": "2302",
    "month_of_event": "February",
    "year_of_event": "1984",
    "independence_from": "United Kingdom",
    "capital": "Bandar Seri Begawan"
  },
  {
    "country_id": "26",
    "country": "Bulgaria",
    "name_of_holiday": "Liberation Day",
    "date_of_holiday": "03/03",
    "date_num": "0303",
    "month_of_event": "March",
    "year_of_event": "1878",
    "independence_from": "Ottoman Empire",
    "capital": "Sofia"
  },
  {
    "country_id": "27",
    "country": "Bulgaria",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "22/09",
    "date_num": "2209",
    "month_of_event": "September",
    "year_of_event": "1908",
    "independence_from": "",
    "capital": "Sofia"
  },
  {
    "country_id": "28",
    "country": "Burkina Faso",
    "name_of_holiday": "Proclamation of Independence Day",
    "date_of_holiday": "11/12",
    "date_num": "1112",
    "month_of_event": "December",
    "year_of_event": "1958",
    "independence_from": "France",
    "capital": "Ouagadougou"
  },
  {
    "country_id": "29",
    "country": "Burkina Faso",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "05/08",
    "date_num": "0508",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "",
    "capital": "Ouagadougou"
  },
  {
    "country_id": "30",
    "country": "Burundi",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/07",
    "date_num": "0107",
    "month_of_event": "July",
    "year_of_event": "1962",
    "independence_from": "Belgium"
  },
  {
    "country_id": "31",
    "country": "Cambodia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "09/11",
    "date_num": "0911",
    "month_of_event": "November",
    "year_of_event": "1953",
    "independence_from": "France",
    "capital": "Phnom Penh"
  },
  {
    "country_id": "32",
    "country": "Cameroon",
    "name_of_holiday": "National Day",
    "date_of_holiday": "20/05",
    "date_num": "2005",
    "month_of_event": "May",
    "year_of_event": "1960",
    "independence_from": "United Kingdom and France",
    "capital": "Yaoundé"
  },
  {
    "country_id": "33",
    "country": "Canada",
    "name_of_holiday": "Canada Day",
    "date_of_holiday": "01/07",
    "date_num": "0107",
    "month_of_event": "July",
    "year_of_event": "1867",
    "independence_from": "United Kingdom",
    "capital": "Ottawa"
  },
  {
    "country_id": "34",
    "country": "Cape Verde",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "05/07",
    "date_num": "0507",
    "month_of_event": "July",
    "year_of_event": "1975",
    "independence_from": "Portugal",
    "capital": "Praia"
  },
  {
    "country_id": "35",
    "country": "Central African Republic",
    "name_of_holiday": "National Day",
    "date_of_holiday": "01/12",
    "date_num": "0112",
    "month_of_event": "December",
    "year_of_event": "1958",
    "independence_from": "France",
    "capital": "Bangui"
  },
  {
    "country_id": "36",
    "country": "Central African Republic",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "13/08",
    "date_num": "1308",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "",
    "capital": "Bangui"
  },
  {
    "country_id": "37",
    "country": "Chad",
    "name_of_holiday": "Republic Day",
    "date_of_holiday": "28/11",
    "date_num": "2811",
    "month_of_event": "November",
    "year_of_event": "1958",
    "independence_from": "",
    "capital": "N'Djamena"
  },
  {
    "country_id": "38",
    "country": "Chad",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "11/08",
    "date_num": "1108",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "",
    "capital": "N'Djamena"
  },
  {
    "country_id": "39",
    "country": "Chile",
    "name_of_holiday": "Independence Day (part of Fiestas Patrias)",
    "date_of_holiday": "18/09",
    "date_num": "1809",
    "month_of_event": "September",
    "year_of_event": "1810",
    "independence_from": "Spanish Empire",
    "capital": "Santiago"
  },
  {
    "country_id": "40",
    "country": "Colombia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "20/07",
    "date_num": "2007",
    "month_of_event": "July",
    "year_of_event": "1810",
    "independence_from": "Spanish Empire",
    "capital": "Bogotá"
  },
  {
    "country_id": "41",
    "country": "Comoros",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "06/07",
    "date_num": "0607",
    "month_of_event": "July",
    "year_of_event": "1975",
    "independence_from": "France",
    "capital": "Moroni"
  },
  {
    "country_id": "42",
    "country": "Congo, Democratic Republic of the",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "30/06",
    "date_num": "3006",
    "month_of_event": "June",
    "year_of_event": "1960",
    "independence_from": "Belgium",
    "capital": "Kinshasa"
  },
  {
    "country_id": "43",
    "country": "Congo, Republic of the",
    "name_of_holiday": "Republic Day",
    "date_of_holiday": "28/11",
    "date_num": "2811",
    "month_of_event": "November",
    "year_of_event": "1958",
    "independence_from": "France",
    "capital": "Brazzaville"
  },
  {
    "country_id": "44",
    "country": "Congo, Republic of the",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "15/08",
    "date_num": "1508",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "",
    "capital": "Brazzaville"
  },
  {
    "country_id": "45",
    "country": "Costa Rica",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "15/09",
    "date_num": "1509",
    "month_of_event": "September",
    "year_of_event": "1821",
    "independence_from": "Spanish Empire",
    "capital": "San José"
  },
  {
    "country_id": "46",
    "country": "Croatia",
    "name_of_holiday": "Statehood Day",
    "date_of_holiday": "30/05",
    "date_num": "3005",
    "month_of_event": "May",
    "year_of_event": "1990",
    "independence_from": "SFR Yugoslavia",
    "capital": "Zagreb"
  },
  {
    "country_id": "47",
    "country": "Cuba",
    "name_of_holiday": "Commencement of the Wars of Independence",
    "date_of_holiday": "10/10",
    "date_num": "1010",
    "month_of_event": "October",
    "year_of_event": "1868",
    "independence_from": "Spanish Empire and United States",
    "capital": "Havana"
  },
  {
    "country_id": "48",
    "country": "Cyprus",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/10",
    "date_num": "0110",
    "month_of_event": "October",
    "year_of_event": "1960",
    "independence_from": "United Kingdom",
    "capital": "Nicosia"
  },
  {
    "country_id": "49",
    "country": "Czech Republic",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "28/10",
    "date_num": "2810",
    "month_of_event": "October",
    "year_of_event": "1918",
    "independence_from": "Austria-Hungary",
    "capital": "Prague"
  },
  {
    "country_id": "50",
    "country": "Czech Republic",
    "name_of_holiday": "Restoration Day",
    "date_of_holiday": "01/01",
    "date_num": "0101",
    "month_of_event": "January",
    "year_of_event": "1993",
    "independence_from": "Czechoslovakia",
    "capital": "Prague"
  },
  {
    "country_id": "51",
    "country": "Djibouti",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "27/06",
    "date_num": "2706",
    "month_of_event": "June",
    "year_of_event": "1977",
    "independence_from": "France",
    "capital": "Djibouti"
  },
  {
    "country_id": "52",
    "country": "Dominica",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "03/11",
    "date_num": "0311",
    "month_of_event": "November",
    "year_of_event": "1978",
    "independence_from": "United Kingdom",
    "capital": "Roseau"
  },
  {
    "country_id": "53",
    "country": "Dominican Republic",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "27/02",
    "date_num": "27/02",
    "month_of_event": "February",
    "year_of_event": "1821 and 1844",
    "independence_from": "Spain, Haiti",
    "capital": "Santo Domingo"
  },
  {
    "country_id": "54",
    "country": "East Timor",
    "name_of_holiday": "Independence Restoration Day",
    "date_of_holiday": "20/05",
    "date_num": "2005",
    "month_of_event": "May",
    "year_of_event": "2002",
    "independence_from": "Indonesia",
    "capital": "Dili"
  },
  {
    "country_id": "55",
    "country": "Ecuador",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "10/08",
    "date_num": "1008",
    "month_of_event": "August",
    "year_of_event": "1809",
    "independence_from": "Spanish Empire",
    "capital": "Quito"
  },
  {
    "country_id": "56",
    "country": "Egypt",
    "name_of_holiday": "Revolution Day",
    "date_of_holiday": "23/07",
    "date_num": "2307",
    "month_of_event": "July",
    "year_of_event": "1952",
    "independence_from": "United Kingdom",
    "capital": "Cairo"
  },
  {
    "country_id": "57",
    "country": "El Salvador",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "15/09",
    "date_num": "1509",
    "month_of_event": "September",
    "year_of_event": "1821",
    "independence_from": "Spanish Empire",
    "capital": "San Salvador"
  },
  {
    "country_id": "58",
    "country": "Equatorial Guinea",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "12/10",
    "date_num": "1210",
    "month_of_event": "October",
    "year_of_event": "1968",
    "independence_from": "Spain",
    "capital": "Malabo"
  },
  {
    "country_id": "59",
    "country": "Eritrea",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "24/05",
    "date_num": "2405",
    "month_of_event": "May",
    "year_of_event": "1991",
    "independence_from": "Ethiopia",
    "capital": "Asmara"
  },
  {
    "country_id": "60",
    "country": "Estonia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "24/02",
    "date_num": "2402",
    "month_of_event": "February",
    "year_of_event": "1918",
    "independence_from": "Russian Soviet Federative Socialist Republic",
    "capital": "Tallinn"
  },
  {
    "country_id": "61",
    "country": "Estonia",
    "name_of_holiday": "Day of Restoration of Independence",
    "date_of_holiday": "20/08",
    "date_num": "2008",
    "month_of_event": "August",
    "year_of_event": "1991",
    "independence_from": "Soviet Union",
    "capital": "Tallinn"
  },
  {
    "country_id": "62",
    "country": "Fiji",
    "name_of_holiday": "Fiji Day",
    "date_of_holiday": "10/10",
    "date_num": "1010",
    "month_of_event": "October",
    "year_of_event": "1970",
    "independence_from": "United Kingdom",
    "capital": "Suva"
  },
  {
    "country_id": "63",
    "country": "Finland",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "06/12",
    "date_num": "0612",
    "month_of_event": "December",
    "year_of_event": "1917",
    "independence_from": "Russian Soviet Federative Socialist Republic",
    "capital": "Helsinki"
  },
  {
    "country_id": "64",
    "country": "Gabon",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "17/08",
    "date_num": "1708",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "France",
    "capital": "Libreville"
  },
  {
    "country_id": "65",
    "country": "Gambia, The",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "18/02",
    "date_num": "1802",
    "month_of_event": "February",
    "year_of_event": "1965",
    "independence_from": "United Kingdom",
    "capital": "Banjul"
  },
  {
    "country_id": "66",
    "country": "Georgia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "26/05",
    "date_num": "2605",
    "month_of_event": "May",
    "year_of_event": "1918",
    "independence_from": "Russian Soviet Federative Socialist Republic",
    "capital": "Tbilisi"
  },
  {
    "country_id": "67",
    "country": "Georgia",
    "name_of_holiday": "Day of National Unity",
    "date_of_holiday": "09/04",
    "date_num": "0904",
    "month_of_event": "April",
    "year_of_event": "1991",
    "independence_from": "Soviet Union",
    "capital": "Tbilisi"
  },
  {
    "country_id": "68",
    "country": "Germany",
    "name_of_holiday": "Day of Unity",
    "date_of_holiday": "03/10",
    "date_num": "0310",
    "month_of_event": "October",
    "year_of_event": "1990",
    "independence_from": "West Germany and East Germany",
    "capital": "Berlin"
  },
  {
    "country_id": "69",
    "country": "Ghana",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "06/03",
    "date_num": "0603",
    "month_of_event": "March",
    "year_of_event": "1957",
    "independence_from": "United Kingdom",
    "capital": "Accra"
  },
  {
    "country_id": "70",
    "country": "Greece",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "25/03",
    "date_num": "2503",
    "month_of_event": "March",
    "year_of_event": "1821",
    "independence_from": "Ottoman Empire",
    "capital": "Athens"
  },
  {
    "country_id": "71",
    "country": "Grenada",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "07/02",
    "date_num": "0702",
    "month_of_event": "February",
    "year_of_event": "1974",
    "independence_from": "United Kingdom",
    "capital": "Saint George's"
  },
  {
    "country_id": "72",
    "country": "Guatemala",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "15/09",
    "date_num": "1509",
    "month_of_event": "September",
    "year_of_event": "1821",
    "independence_from": "Spanish Empire",
    "capital": "Guatemala City"
  },
  {
    "country_id": "73",
    "country": "Guinea",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "02/10",
    "date_num": "0210",
    "month_of_event": "October",
    "year_of_event": "1958",
    "independence_from": "France",
    "capital": "Conakry"
  },
  {
    "country_id": "74",
    "country": "Guinea-Bissau",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "24/09",
    "date_num": "2409",
    "month_of_event": "September",
    "year_of_event": "1973",
    "independence_from": "Portugal"
  },
  {
    "country_id": "75",
    "country": "Guyana",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "26/05",
    "date_num": "2605",
    "month_of_event": "May",
    "year_of_event": "1966",
    "independence_from": "United Kingdom",
    "capital": "Georgetown"
  },
  {
    "country_id": "76",
    "country": "Haiti",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/01",
    "date_num": "0101",
    "month_of_event": "January",
    "year_of_event": "1804",
    "independence_from": "France",
    "capital": "Port-au-Prince"
  },
  {
    "country_id": "77",
    "country": "Honduras",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "15/09",
    "date_num": "1509",
    "month_of_event": "September",
    "year_of_event": "1821",
    "independence_from": "Spanish Empire",
    "capital": "Tegucigalpa"
  },
  {
    "country_id": "78",
    "country": "Hungary",
    "name_of_holiday": "Day of Hungarian Freedom",
    "date_of_holiday": "23/10",
    "date_num": "2310",
    "month_of_event": "October",
    "year_of_event": "1991",
    "independence_from": "",
    "capital": "Budapest"
  },
  {
    "country_id": "79",
    "country": "Iceland",
    "name_of_holiday": "National Day",
    "date_of_holiday": "17/06",
    "date_num": "1706",
    "month_of_event": "June",
    "year_of_event": "1944",
    "independence_from": "Denmark",
    "capital": "Reykjavík"
  },
  {
    "country_id": "80",
    "country": "India",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "15/08",
    "date_num": "1508",
    "month_of_event": "August",
    "year_of_event": "1947",
    "independence_from": "United Kingdom",
    "capital": "New Delhi"
  },
  {
    "country_id": "81",
    "country": "Indonesia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "17/08",
    "date_num": "1708",
    "month_of_event": "August",
    "year_of_event": "1945",
    "independence_from": "Netherlands and Japan",
    "capital": "Jakarta"
  },
  {
    "country_id": "82",
    "country": "Iran",
    "name_of_holiday": "Iranian Islamic Republic Day",
    "date_of_holiday": "01/04",
    "date_num": "0104",
    "month_of_event": "April",
    "year_of_event": "1979",
    "independence_from": "",
    "capital": "Tehran"
  },
  {
    "country_id": "83",
    "country": "Iraq",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "03/10",
    "date_num": "0310",
    "month_of_event": "October",
    "year_of_event": "1932",
    "independence_from": "United Kingdom",
    "capital": "Baghdad"
  },
  {
    "country_id": "84",
    "country": "Israel",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "29/04",
    "date_num": "2904",
    "month_of_event": "April",
    "year_of_event": "1948",
    "independence_from": "United Kingdom and the British Mandate for Palestine",
    "capital": "Jerusalem"
  },
  {
    "country_id": "85",
    "country": "Côte d'Ivoire",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "07/08",
    "date_num": "0708",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "France",
    "capital": "Yamoussoukro"
  },
  {
    "country_id": "86",
    "country": "Jamaica",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "06/08",
    "date_num": "0608",
    "month_of_event": "August",
    "year_of_event": "1962",
    "independence_from": "United Kingdom",
    "capital": "Kingston"
  },
  {
    "country_id": "87",
    "country": "Jordan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "25/05",
    "date_num": "2505",
    "month_of_event": "May",
    "year_of_event": "1946",
    "independence_from": "",
    "capital": "Amman"
  },
  {
    "country_id": "88",
    "country": "Kazakhstan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "16/12",
    "date_num": "1612",
    "month_of_event": "December",
    "year_of_event": "1991",
    "independence_from": "Soviet Union",
    "capital": "Nur-Sultan"
  },
  {
    "country_id": "89",
    "country": "Kenya",
    "name_of_holiday": "Jamhuri Day",
    "date_of_holiday": "12/12",
    "date_num": "1212",
    "month_of_event": "December",
    "year_of_event": "1963",
    "independence_from": "United Kingdom",
    "capital": "Nairobi"
  },
  {
    "country_id": "90",
    "country": "Kiribati",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "12/07",
    "date_num": "1207",
    "month_of_event": "July",
    "year_of_event": "1979",
    "independence_from": "",
    "capital": "Tarawa"
  },
  {
    "country_id": "91",
    "country": "North Korea",
    "name_of_holiday": "National Liberation Day of Korea",
    "date_of_holiday": "15/08",
    "date_num": "1508",
    "month_of_event": "August",
    "year_of_event": "1945",
    "independence_from": "Empire of Japan",
    "capital": "Pyongyang"
  },
  {
    "country_id": "92",
    "country": "South Korea",
    "name_of_holiday": "1 Marchst Movement",
    "date_of_holiday": "01/03",
    "date_num": "0103",
    "month_of_event": "March",
    "year_of_event": "1919",
    "independence_from": "Empire of Japan",
    "capital": "Seoul"
  },
  {
    "country_id": "93",
    "country": "South Korea",
    "name_of_holiday": "National Liberation Day of Korea",
    "date_of_holiday": "15/08",
    "date_num": "1508",
    "month_of_event": "August",
    "year_of_event": "1945",
    "independence_from": "",
    "capital": "Seoul"
  },
  {
    "country_id": "94",
    "country": "Kuwait",
    "name_of_holiday": "National Day",
    "date_of_holiday": "25/02",
    "date_num": "2502",
    "month_of_event": "February",
    "year_of_event": "1961",
    "independence_from": "United Kingdom",
    "capital": "Kuwait City"
  },
  {
    "country_id": "95",
    "country": "Kyrgyzstan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "31/08",
    "date_num": "3108",
    "month_of_event": "August",
    "year_of_event": "1991",
    "independence_from": "Soviet Union",
    "capital": "Bishkek"
  },
  {
    "country_id": "96",
    "country": "Latvia",
    "name_of_holiday": "Proclamation Day of the Republic of Latvia",
    "date_of_holiday": "18/11",
    "date_num": "1811",
    "month_of_event": "November",
    "year_of_event": "1918",
    "independence_from": "Russian Soviet Federative Socialist Republic and German Empire",
    "capital": "Riga"
  },
  {
    "country_id": "97",
    "country": "Latvia",
    "name_of_holiday": "Day of Restoration of Independence",
    "date_of_holiday": "04/05",
    "date_num": "0405",
    "month_of_event": "May",
    "year_of_event": "1990",
    "independence_from": "Soviet Union",
    "capital": "Riga"
  },
  {
    "country_id": "98",
    "country": "Lebanon",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "22/11",
    "date_num": "2211",
    "month_of_event": "November",
    "year_of_event": "1943",
    "independence_from": "France",
    "capital": "Beirut"
  },
  {
    "country_id": "99",
    "country": "Lesotho",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "04/10",
    "date_num": "0410",
    "month_of_event": "October",
    "year_of_event": "1966",
    "independence_from": "United Kingdom",
    "capital": "Maseru"
  },
  {
    "country_id": "100",
    "country": "Liberia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "26/07",
    "date_num": "2607",
    "month_of_event": "July",
    "year_of_event": "1847",
    "independence_from": "American Colonization Society",
    "capital": "Monrovia"
  },
  {
    "country_id": "101",
    "country": "Libya",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "24/12",
    "date_num": "2412",
    "month_of_event": "December",
    "year_of_event": "1951",
    "independence_from": "United Kingdom, Italy and France",
    "capital": "Tripoli"
  },
  {
    "country_id": "102",
    "country": "Liechtenstein",
    "name_of_holiday": "National Day",
    "date_of_holiday": "15/08",
    "date_num": "1508",
    "month_of_event": "August",
    "year_of_event": "1886",
    "independence_from": "German Confederation"
  },
  {
    "country_id": "103",
    "country": "Lithuania",
    "name_of_holiday": "Statehood Restoration Day",
    "date_of_holiday": "16/02",
    "date_num": "1602",
    "month_of_event": "February",
    "year_of_event": "1918",
    "independence_from": "Russian Soviet Federative Socialist Republic and German Empire"
  },
  {
    "country_id": "104",
    "country": "Lithuania",
    "name_of_holiday": "Independence Restoration Day",
    "date_of_holiday": "11/03",
    "date_num": "1103",
    "month_of_event": "March",
    "year_of_event": "1990",
    "independence_from": "Soviet Union"
  },
  {
    "country_id": "105",
    "country": "Madagascar",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "26/06",
    "date_num": "2606",
    "month_of_event": "June",
    "year_of_event": "1960",
    "independence_from": "France"
  },
  {
    "country_id": "106",
    "country": "Malawi",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "06/07",
    "date_num": "0607",
    "month_of_event": "July",
    "year_of_event": "1964",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "107",
    "country": "Malaysia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "31/08",
    "date_num": "3108",
    "month_of_event": "August",
    "year_of_event": "1957"
  },
  {
    "country_id": "108",
    "country": "Maldives",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "26/07",
    "date_num": "2607",
    "month_of_event": "July",
    "year_of_event": "1965"
  },
  {
    "country_id": "109",
    "country": "Mali",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "22/09",
    "date_num": "2209",
    "month_of_event": "September",
    "year_of_event": "1960",
    "independence_from": "France",
    "capital": "Bamako"
  },
  {
    "country_id": "110",
    "country": "Malta",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "21/09",
    "date_num": "2109",
    "month_of_event": "September",
    "year_of_event": "1964",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "111",
    "country": "Marshall Islands",
    "name_of_holiday": "Constitution Day",
    "date_of_holiday": "01/05",
    "date_num": "0105",
    "month_of_event": "May",
    "year_of_event": "1979",
    "independence_from": "United States"
  },
  {
    "country_id": "112",
    "country": "Mauritania",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "28/11",
    "date_num": "2811",
    "month_of_event": "November",
    "year_of_event": "1960",
    "independence_from": "France"
  },
  {
    "country_id": "113",
    "country": "Mauritius",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "12/03",
    "date_num": "1203",
    "month_of_event": "March",
    "year_of_event": "1968",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "114",
    "country": "Mexico",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "16/09",
    "date_num": "1609",
    "month_of_event": "September",
    "year_of_event": "1810",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "115",
    "country": "Micronesia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "03/11",
    "date_num": "0311",
    "month_of_event": "November",
    "year_of_event": "1986",
    "independence_from": "United States"
  },
  {
    "country_id": "116",
    "country": "Moldova",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "27/08",
    "date_num": "2708",
    "month_of_event": "August",
    "year_of_event": "1991",
    "independence_from": "Soviet Union"
  },
  {
    "country_id": "117",
    "country": "Mongolia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "29/12",
    "date_num": "2912",
    "month_of_event": "December",
    "year_of_event": "1911",
    "independence_from": "Qing China[58][59]"
  },
  {
    "country_id": "118",
    "country": "Montenegro",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "21/05",
    "date_num": "2105",
    "month_of_event": "May",
    "year_of_event": "2006",
    "independence_from": "Serbia and Montenegro"
  },
  {
    "country_id": "119",
    "country": "Morocco",
    "name_of_holiday": "Proclamation of Independence Day",
    "date_of_holiday": "11/01",
    "date_num": "1101",
    "month_of_event": "January",
    "year_of_event": "1944",
    "independence_from": "France and Spain"
  },
  {
    "country_id": "120",
    "country": "Morocco",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "18/11",
    "date_num": "1811",
    "month_of_event": "November",
    "year_of_event": "1955"
  },
  {
    "country_id": "121",
    "country": "Mozambique",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "25/06",
    "date_num": "2506",
    "month_of_event": "June",
    "year_of_event": "1975",
    "independence_from": "Portugal"
  },
  {
    "country_id": "122",
    "country": "Myanmar",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "04/01",
    "date_num": "0401",
    "month_of_event": "January",
    "year_of_event": "1948",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "123",
    "country": "Namibia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "21/03",
    "date_num": "2103",
    "month_of_event": "March",
    "year_of_event": "1990",
    "independence_from": "South Africa"
  },
  {
    "country_id": "124",
    "country": "Nauru",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "31/01",
    "date_num": "3101",
    "month_of_event": "January",
    "year_of_event": "1968",
    "independence_from": "United Kingdom, Australia, New Zealand"
  },
  {
    "country_id": "125",
    "country": "Netherlands",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "26/07",
    "date_num": "2607",
    "month_of_event": "July",
    "year_of_event": "1581",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "126",
    "country": "Nicaragua",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "15/09",
    "date_num": "1509",
    "month_of_event": "September",
    "year_of_event": "1821",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "127",
    "country": "Niger",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "03/08",
    "date_num": "0308",
    "month_of_event": "August",
    "year_of_event": "1960",
    "independence_from": "France"
  },
  {
    "country_id": "128",
    "country": "Nigeria",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/10",
    "date_num": "0110",
    "month_of_event": "October",
    "year_of_event": "1960",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "129",
    "country": "North Macedonia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "08/09",
    "date_num": "0809",
    "month_of_event": "September",
    "year_of_event": "1991",
    "independence_from": "SFR Yugoslavia"
  },
  {
    "country_id": "130",
    "country": "Norway",
    "name_of_holiday": "Constitution Day",
    "date_of_holiday": "17/05",
    "date_num": "1705",
    "month_of_event": "May",
    "year_of_event": "1814",
    "independence_from": "Denmark"
  },
  {
    "country_id": "131",
    "country": "Norway",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "07/06",
    "date_num": "0706",
    "month_of_event": "June",
    "year_of_event": "1905",
    "independence_from": "Sweden"
  },
  {
    "country_id": "132",
    "country": "Oman",
    "name_of_holiday": "National Day",
    "date_of_holiday": "18/11",
    "date_num": "1811",
    "month_of_event": "November",
    "year_of_event": "1650",
    "independence_from": "Portugal"
  },
  {
    "country_id": "133",
    "country": "Pakistan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "14/08",
    "date_num": "1408",
    "month_of_event": "August",
    "year_of_event": "1947",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "134",
    "country": "Palau",
    "name_of_holiday": "Constitution Day",
    "date_of_holiday": "09/07",
    "date_num": "0907",
    "month_of_event": "July",
    "year_of_event": "1980"
  },
  {
    "country_id": "135",
    "country": "Palestine",
    "name_of_holiday": "National Day",
    "date_of_holiday": "15/11",
    "date_num": "1511",
    "month_of_event": "November",
    "year_of_event": "1988",
    "independence_from": "Israel"
  },
  {
    "country_id": "136",
    "country": "Panama",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "28/11",
    "date_num": "2811",
    "month_of_event": "November",
    "year_of_event": "1821",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "137",
    "country": "Panama",
    "name_of_holiday": "Separation Day",
    "date_of_holiday": "03/11",
    "date_num": "0311",
    "month_of_event": "November",
    "year_of_event": "1903",
    "independence_from": "Colombia"
  },
  {
    "country_id": "138",
    "country": "Papua New Guinea",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "16/09",
    "date_num": "1609",
    "month_of_event": "September",
    "year_of_event": "1975",
    "independence_from": "Australia of the former Territory of Papua and New Guinea"
  },
  {
    "country_id": "139",
    "country": "Paraguay",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "14/05",
    "date_num": "1405",
    "month_of_event": "May",
    "year_of_event": "1811",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "140",
    "country": "Peru",
    "name_of_holiday": "Fiestas Patrias",
    "date_of_holiday": "28/07",
    "date_num": "2807",
    "month_of_event": "July",
    "year_of_event": "1821",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "141",
    "country": "Philippines",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "12/06",
    "date_num": "1206",
    "month_of_event": "June",
    "year_of_event": "1898"
  },
  {
    "country_id": "142",
    "country": "Poland",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "11/11",
    "date_num": "1111",
    "month_of_event": "November",
    "year_of_event": "1918",
    "independence_from": "Russian Soviet Federative Socialist Republic and German Empire"
  },
  {
    "country_id": "143",
    "country": "Portugal",
    "name_of_holiday": "Restoration of Independence Day",
    "date_of_holiday": "01/12",
    "date_num": "0112",
    "month_of_event": "December",
    "year_of_event": "1640",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "144",
    "country": "Qatar",
    "name_of_holiday": "National Day",
    "date_of_holiday": "18/12",
    "date_num": "1812",
    "month_of_event": "December",
    "year_of_event": "1971",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "145",
    "country": "Romania",
    "name_of_holiday": "State Independence Day of Romania",
    "date_of_holiday": "09/05",
    "date_num": "0905",
    "month_of_event": "May",
    "year_of_event": "1877",
    "independence_from": "Ottoman Empire"
  },
  {
    "country_id": "146",
    "country": "Russia",
    "name_of_holiday": "Russia Day",
    "date_of_holiday": "12/06",
    "date_num": "1206",
    "month_of_event": "June",
    "year_of_event": "1992",
    "independence_from": "Soviet Union"
  },
  {
    "country_id": "147",
    "country": "Rwanda",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/07",
    "date_num": "0107",
    "month_of_event": "July",
    "year_of_event": "1962",
    "independence_from": "Belgium"
  },
  {
    "country_id": "148",
    "country": "Saint Kitts and Nevis",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "19/09",
    "date_num": "1909",
    "month_of_event": "September",
    "year_of_event": "1983",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "149",
    "country": "Saint Lucia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "22/02",
    "date_num": "2202",
    "month_of_event": "February",
    "year_of_event": "1979"
  },
  {
    "country_id": "150",
    "country": "Saint Vincent and the Grenadines",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "27/10",
    "date_num": "2710",
    "month_of_event": "October",
    "year_of_event": "1979"
  },
  {
    "country_id": "151",
    "country": "Samoa",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/06",
    "date_num": "0106",
    "month_of_event": "June",
    "year_of_event": "1962",
    "independence_from": "New Zealand"
  },
  {
    "country_id": "152",
    "country": "São Tomé and Príncipe",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "12/07",
    "date_num": "1207",
    "month_of_event": "July",
    "year_of_event": "1975",
    "independence_from": "Portugal"
  },
  {
    "country_id": "153",
    "country": "Senegal",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "04/04",
    "date_num": "0404",
    "month_of_event": "April",
    "year_of_event": "1960",
    "independence_from": "France"
  },
  {
    "country_id": "154",
    "country": "Serbia",
    "name_of_holiday": "Statehood Day",
    "date_of_holiday": "15/02",
    "date_num": "1502",
    "month_of_event": "February",
    "year_of_event": "1804 and 1835",
    "independence_from": "Ottoman Empire"
  },
  {
    "country_id": "155",
    "country": "Seychelles",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "29/06",
    "date_num": "2906",
    "month_of_event": "June",
    "year_of_event": "1976",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "156",
    "country": "Sierra Leone",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "27/04",
    "date_num": "2704",
    "month_of_event": "April",
    "year_of_event": "1961"
  },
  {
    "country_id": "157",
    "country": "Singapore",
    "name_of_holiday": "National Day",
    "date_of_holiday": "09/08",
    "date_num": "0908",
    "month_of_event": "August",
    "year_of_event": "1965",
    "independence_from": "Malaysia"
  },
  {
    "country_id": "158",
    "country": "Slovakia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "17/07",
    "date_num": "1707",
    "month_of_event": "July",
    "year_of_event": "1992",
    "independence_from": "Czechoslovakia"
  },
  {
    "country_id": "159",
    "country": "Slovenia",
    "name_of_holiday": "Independence and Unity Day",
    "date_of_holiday": "25/06",
    "date_num": "2506",
    "month_of_event": "June",
    "year_of_event": "1991",
    "independence_from": "SFR Yugoslavia"
  },
  {
    "country_id": "160",
    "country": "Solomon Islands",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "07/07",
    "date_num": "0707",
    "month_of_event": "July",
    "year_of_event": "1978",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "161",
    "country": "Somalia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/07",
    "date_num": "0107",
    "month_of_event": "July",
    "year_of_event": "1960",
    "independence_from": "United Kingdom, Italy"
  },
  {
    "country_id": "162",
    "country": "Somaliland",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "18/05",
    "date_num": "1805",
    "month_of_event": "May",
    "year_of_event": "1991",
    "independence_from": "Somali Democratic Republic"
  },
  {
    "country_id": "163",
    "country": "South Sudan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "09/07",
    "date_num": "0907",
    "month_of_event": "July",
    "year_of_event": "2011",
    "independence_from": "Sudan"
  },
  {
    "country_id": "164",
    "country": "Sri Lanka",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "04/02",
    "date_num": "0402",
    "month_of_event": "February",
    "year_of_event": "1948",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "165",
    "country": "Sudan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/01",
    "date_num": "0101",
    "month_of_event": "January",
    "year_of_event": "1956",
    "independence_from": "United Kingdom and Egypt"
  },
  {
    "country_id": "166",
    "country": "Suriname",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "25/11",
    "date_num": "2511",
    "month_of_event": "November",
    "year_of_event": "1975",
    "independence_from": "Netherlands"
  },
  {
    "country_id": "167",
    "country": "Sweden",
    "name_of_holiday": "National Day",
    "date_of_holiday": "06/06",
    "date_num": "0606",
    "month_of_event": "June",
    "year_of_event": "1523",
    "independence_from": "Kalmar Union"
  },
  {
    "country_id": "168",
    "country": "Switzerland",
    "name_of_holiday": "Swiss National Day",
    "date_of_holiday": "01/08",
    "date_num": "0108",
    "month_of_event": "August",
    "year_of_event": "1291",
    "independence_from": "Holy Roman Empire"
  },
  {
    "country_id": "169",
    "country": "Syria",
    "name_of_holiday": "Evacuation Day",
    "date_of_holiday": "17/04",
    "date_num": "1704",
    "month_of_event": "April",
    "year_of_event": "1946",
    "independence_from": "France"
  },
  {
    "country_id": "170",
    "country": "Tajikistan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "09/09",
    "date_num": "0909",
    "month_of_event": "September",
    "year_of_event": "1991",
    "independence_from": "Soviet Union"
  },
  {
    "country_id": "171",
    "country": "Tanzania",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "09/12",
    "date_num": "0912",
    "month_of_event": "December",
    "year_of_event": "1961",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "172",
    "country": "Togo",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "27/04",
    "date_num": "2704",
    "month_of_event": "April",
    "year_of_event": "1960",
    "independence_from": "France"
  },
  {
    "country_id": "173",
    "country": "Tonga",
    "name_of_holiday": "Emancipation Day",
    "date_of_holiday": "04/06",
    "date_num": "0406",
    "month_of_event": "June",
    "year_of_event": "1970",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "174",
    "country": "Trinidad and Tobago",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "31/08",
    "date_num": "3108",
    "month_of_event": "August",
    "year_of_event": "1962"
  },
  {
    "country_id": "175",
    "country": "Tunisia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "20/03",
    "date_num": "2003",
    "month_of_event": "March",
    "year_of_event": "1956",
    "independence_from": "France"
  },
  {
    "country_id": "176",
    "country": "Turkmenistan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "27/09",
    "date_num": "2709",
    "month_of_event": "September",
    "year_of_event": "1991",
    "independence_from": "Soviet Union"
  },
  {
    "country_id": "177",
    "country": "Tuvalu",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/10",
    "date_num": "0110",
    "month_of_event": "October",
    "year_of_event": "1978",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "178",
    "country": "Uganda",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "09/10",
    "date_num": "0910",
    "month_of_event": "October",
    "year_of_event": "1962"
  },
  {
    "country_id": "179",
    "country": "Ukraine",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "24/08",
    "date_num": "2408",
    "month_of_event": "August",
    "year_of_event": "1991",
    "independence_from": "Soviet Union"
  },
  {
    "country_id": "180",
    "country": "United Arab Emirates",
    "name_of_holiday": "National Day",
    "date_of_holiday": "02/12",
    "date_num": "0212",
    "month_of_event": "December",
    "year_of_event": "1971",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "181",
    "country": "United States",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "04/07",
    "date_num": "0407",
    "month_of_event": "July",
    "year_of_event": "1776",
    "independence_from": "Kingdom of Great Britain"
  },
  {
    "country_id": "182",
    "country": "Uruguay",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "25/08",
    "date_num": "2508",
    "month_of_event": "August",
    "year_of_event": "1825",
    "independence_from": "United Provinces of the Río de la Plata"
  },
  {
    "country_id": "183",
    "country": "Uzbekistan",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "01/09",
    "date_num": "0109",
    "month_of_event": "September",
    "year_of_event": "1991",
    "independence_from": "Soviet Union"
  },
  {
    "country_id": "184",
    "country": "Vanuatu",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "30/7",
    "date_num": "3007",
    "month_of_event": "July",
    "year_of_event": "1980",
    "independence_from": "United Kingdom and France"
  },
  {
    "country_id": "185",
    "country": "Vatican City",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "11/02",
    "date_num": "1102",
    "month_of_event": "February",
    "year_of_event": "1929",
    "independence_from": "Italy"
  },
  {
    "country_id": "186",
    "country": "Venezuela",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "05/07",
    "date_num": "0507",
    "month_of_event": "July",
    "year_of_event": "1811",
    "independence_from": "Spanish Empire"
  },
  {
    "country_id": "187",
    "country": "Vietnam",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "02/09",
    "date_num": "0209",
    "month_of_event": "September",
    "year_of_event": "1945",
    "independence_from": "Empire of Japan and France"
  },
  {
    "country_id": "188",
    "country": "Yemen",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "30/11",
    "date_num": "3011",
    "month_of_event": "November",
    "year_of_event": "1967",
    "independence_from": "United Kingdom"
  },
  {
    "country_id": "189",
    "country": "Zambia",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "24/10",
    "date_num": "2410",
    "month_of_event": "October",
    "year_of_event": "1964",
    "independence_from": "",
    "capital": "Lusaka"
  },
  {
    "country_id": "190",
    "country": "Zimbabwe",
    "name_of_holiday": "Independence Day",
    "date_of_holiday": "18/04",
    "date_num": "1804",
    "month_of_event": "April",
    "year_of_event": "1980",
    "independence_from": "",
    "capital": "Harare"
  }
]
module.exports = dataApi;